import { Event } from './types';

export const seedEvents: Event[] = [
  {
    id: '1',
    title: 'Ringana Spring Launch Vienna',
    description: 'Join us for the exclusive spring product launch in Vienna! Experience the newest RINGANA freshcosmetics and supplements firsthand. Network with fellow partners and learn about exciting new business opportunities.',
    date: '2026-05-10',
    time: '14:00',
    endTime: '18:00',
    location: 'Grand Hotel Wien, Kärntner Ring 9',
    city: 'Vienna',
    country: 'Austria',
    isOnline: false,
    audience: 'partners',
    ticketUrl: 'https://ringana.com/events/spring-launch',
    isFree: false,
    price: '€25',
    organizer: {
      name: 'Maria Gruber',
      email: 'maria.gruber@ringana.com',
      role: 'Regional Manager AT',
    },
    tags: ['launch', 'networking', 'products'],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Wellness Day for Customers – Munich',
    description: 'A full day of wellness, yoga, and RINGANA product experiences for our valued customers. Includes workshops, massages, and product tastings. Bring a friend!',
    date: '2026-05-18',
    time: '10:00',
    endTime: '17:00',
    location: 'Olympiapark Munich',
    city: 'Munich',
    country: 'Germany',
    isOnline: false,
    audience: 'customers',
    ticketUrl: 'https://ringana.com/events/wellness-munich',
    isFree: false,
    price: '€15',
    organizer: {
      name: 'Thomas Bauer',
      email: 'thomas.bauer@ringana.com',
      role: 'Partner DE',
    },
    tags: ['wellness', 'yoga', 'customers', 'experience'],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Online Partner Training – Summer Strategy',
    description: 'Virtual training session for all RINGANA partners. We will cover the summer marketing strategy, new tools, and answer your questions live. Recording available afterwards.',
    date: '2026-05-25',
    time: '19:00',
    endTime: '20:30',
    location: 'Zoom',
    city: 'Online',
    country: 'International',
    isOnline: true,
    audience: 'partners',
    ticketUrl: 'https://ringana.com/events/online-training-summer',
    isFree: true,
    organizer: {
      name: 'RINGANA Academy',
      email: 'academy@ringana.com',
      role: 'Training Team',
    },
    tags: ['training', 'online', 'strategy', 'partners'],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Team Kick-off Q3 – Hartberg HQ',
    description: 'Internal team meeting at RINGANA headquarters in Hartberg. Agenda includes Q2 review, Q3 goals, new product development overview, and team building activities.',
    date: '2026-06-05',
    time: '09:00',
    endTime: '17:00',
    location: 'RINGANA Campus, Hartberg',
    city: 'Hartberg',
    country: 'Austria',
    isOnline: false,
    audience: 'team',
    isFree: true,
    organizer: {
      name: 'RINGANA Management',
      email: 'team@ringana.com',
      role: 'Management',
    },
    tags: ['team', 'internal', 'kickoff', 'Q3'],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'RINGANA Open Day Zurich',
    description: 'Open doors event for interested customers and potential new partners in Zurich. Free entry, product samples, and personal consultations available.',
    date: '2026-06-14',
    time: '11:00',
    endTime: '16:00',
    location: 'Hotel Widder, Rennweg 7',
    city: 'Zurich',
    country: 'Switzerland',
    isOnline: false,
    audience: 'all',
    ticketUrl: 'https://ringana.com/events/open-day-zurich',
    isFree: true,
    organizer: {
      name: 'Claudia Meier',
      email: 'claudia.meier@ringana.com',
      role: 'Partner CH',
    },
    tags: ['open-day', 'networking', 'all-welcome'],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
