import { Event } from './types';

export const seedEvents: Event[] = [
  {
    id: '1',
    title: 'RINGANA Partner Frühlings-Launch Wien',
    description: 'Komm zum exklusiven Frühlings-Produkt-Launch in Wien! Erlebe die neuesten RINGANA freshcosmetics und Supplements hautnah. Vernetze dich mit anderen Partnern und erfahre alles über spannende neue Geschäftsmöglichkeiten.',
    date: '2026-05-10',
    time: '14:00',
    endTime: '18:00',
    location: 'Grand Hotel Wien, Kärntner Ring 9',
    city: 'Wien',
    country: 'Österreich',
    isOnline: false,
    audience: 'partners',
    ticketUrl: 'https://ringana.com/events/spring-launch',
    isFree: false,
    price: '€25',
    organizer: {
      name: 'Maria Gruber',
      email: 'maria.gruber@partner.ringana.com',
      role: 'Regionalleiterin AT',
    },
    tags: ['launch', 'netzwerken', 'produkte'],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Wellness-Tag für Kunden – München',
    description: 'Ein ganzer Tag voller Wellness, Yoga und RINGANA Produkterlebnisse für unsere geschätzten Kunden. Inklusive Workshops, Massagen und Produktverkostungen. Bring eine Freundin mit!',
    date: '2026-05-18',
    time: '10:00',
    endTime: '17:00',
    location: 'Olympiapark München',
    city: 'München',
    country: 'Deutschland',
    isOnline: false,
    audience: 'customers',
    ticketUrl: 'https://ringana.com/events/wellness-munich',
    isFree: false,
    price: '€15',
    organizer: {
      name: 'Thomas Bauer',
      email: 'thomas.bauer@partner.ringana.com',
      role: 'Partner DE',
    },
    tags: ['wellness', 'yoga', 'kunden', 'erlebnis'],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Online Partner Training – Sommerstrategie',
    description: 'Virtuelles Training für alle RINGANA Partner. Wir besprechen die Sommerstrategie, neue Tools und beantworten eure Fragen live. Die Aufzeichnung ist danach verfügbar.',
    date: '2026-05-25',
    time: '19:00',
    endTime: '20:30',
    location: 'Zoom',
    city: 'Online',
    country: 'International',
    isOnline: true,
    audience: 'partners',
    ticketUrl: 'https://ringana.com/events/online-training-summer',
    isFree: true,
    organizer: {
      name: 'RINGANA Academy',
      email: 'academy@ringana.com',
      role: 'Training Team',
    },
    tags: ['training', 'online', 'strategie', 'partner'],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Team Kick-off Q3 – Hartberg HQ',
    description: 'Internes Team-Meeting am RINGANA Campus in Hartberg. Agenda: Q2-Review, Q3-Ziele, Produktentwicklung und Team-Building-Aktivitäten.',
    date: '2026-06-05',
    time: '09:00',
    endTime: '17:00',
    location: 'RINGANA Campus, Hartberg',
    city: 'Hartberg',
    country: 'Österreich',
    isOnline: false,
    audience: 'team',
    isFree: true,
    organizer: {
      name: 'RINGANA Management',
      email: 'team@ringana.com',
      role: 'Management',
    },
    tags: ['team', 'intern', 'kickoff', 'Q3'],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'RINGANA Open Day Zürich',
    description: 'Offene Türen für interessierte Kunden und potenzielle neue Partner in Zürich. Freier Eintritt, Produktproben und persönliche Beratungsgespräche vor Ort.',
    date: '2026-06-14',
    time: '11:00',
    endTime: '16:00',
    location: 'Hotel Widder, Rennweg 7',
    city: 'Zürich',
    country: 'Schweiz',
    isOnline: false,
    audience: 'all',
    ticketUrl: 'https://ringana.com/events/open-day-zurich',
    isFree: true,
    organizer: {
      name: 'Claudia Meier',
      email: 'claudia.meier@partner.ringana.com',
      role: 'Partnerin CH',
    },
    tags: ['open-day', 'netzwerken', 'alle-willkommen'],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
